final Map<String, dynamic> mapSensorName = {
  "ACCELEROMETER_UNCALIBRATED": "Acelerômetro (não calibrado)",
  "ACCELEROMETER": "Acelerômetro",
  "AMBIENT_TEMPERATURE": "Temperatura ambiente",
  "GAME ROTATION VECTOR": "Game Rotation Vector",
  "GEOMAGNETIC_ROTATION_VECTOR": "Geomagnetic Rotation Vector",
  "GRAVITY": "Gravidade",
  "GYROSCOPE_UNCALIBRATED": "Giroscópio (não calibrado)",
  "GYROSCOPE": "Giroscópio",
  "HEART_RATE": "Frequência cardíaca",
  "LIGHT": "Sensor de luz ambiente",
  "LINEAR_ACCELERATION": "Aceleração linear",
  "MAGNETIC_FIELD_UNCALIBRATED": "Magnetômetro (não calibrado)",
  "MAGNETIC_FIELD": "Magnetômetro",
  "MOTION_DETECT": "Detecção de movimento",
  "ORIENTATION": "Orientação (deprecated)",
  "POSE_6DOF": "Pose 6DoF",
  "PRESSURE": "Pressão (Barômetro)",
  "PROXIMITY": "Proximidade",
  "RELATIVE_HUMIDITY": "Umidade relativa",
  "ROTATION_VECTOR": "Rotation Vector",
  "SIGNIFICANT_MOTION": "Significant Motion",
  "STEP_COUNTER": "Contador de passos",
  "STEP_DETECTOR": "Detector de passos",
  "STATIONARY_DETECT": "Stationary Detect",
  "TEMPERATURE": "Temperatura (deprecated)",
  "LOW_LATENCY_OFFBODY_DETECT": "Off-body detect",
  "MAGNETOMETER": "Magnetometer",
};
